---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 2023-consumer
  name: 2023-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2023-consumer
  template:
    metadata:
      labels:
        app: 2023-consumer
      annotations:
        polarismesh.cn/javaagent: "true"
        polarismesh.cn/javaagentVersion: "1.6.1"
        polarismesh.cn/javaagentFrameworkName: "spring-cloud"
        polarismesh.cn/javaagentFrameworkVersion: "2023"
        polarismesh.cn/javaagentConfig: "{\"spring.cloud.polaris.lossless.enabled\": \"true\", \"spring.cloud.polaris.namespace\": \"default\"}"
    spec:
      containers:
        - image: polarismesh/polaris-javaagent-demo-sc-quickstart-2023-consumer:1.6.1-java17
          imagePullPolicy: Always
          name: consumer
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command:
            - /bin/bash
            - -c
            - cd /app && java -Dspring.cloud.nacos.config.server-addr=10.0.90.37:8848 -Dserver.port=65101 -jar main.jar
          lifecycle:
            preStop:
              exec:
                command: ["curl","-X","PUT","http://127.0.0.1:28080/offline","&&","sleep","30"]
          readinessProbe:
            httpGet:
              path: /online
              port: 28080
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always