---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hoxton-callee
  name: hoxton-callee
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoxton-callee
  template:
    metadata:
      labels:
        app: hoxton-callee
      annotations:
        polarismesh.cn/javaagent: "true"
        polarismesh.cn/javaagentVersion: "1.7.0-RC2"
        polarismesh.cn/javaagentFrameworkName: "spring-cloud"
        polarismesh.cn/javaagentFrameworkVersion: "hoxton"
    spec:
      containers:
        - image: polarismesh/polaris-javaagent-demo-sc-quickstart-hoxton-callee:1.7.0-java8
          imagePullPolicy: Always
          name: provider
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command:
            - /bin/bash
            - -c
            - cd /app && java -Dserver.port=48083 -jar main.jar
          lifecycle:
            preStop:
              exec:
                command: ["curl","-X","PUT","http://127.0.0.1:28080/offline","&&","sleep","30"]
          readinessProbe:
            httpGet:
              path: /online
              port: 28080
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always