#server:
#  port: 65101
#
#spring:
#  application:
#    name: service-consumer-2023
#  cloud:
#    nacos:
#      discovery:
#        enabled: false
#        server-addr: 127.0.0.1:8848
#      config:
#        enabled: false
#        serverAddr: 127.0.0.1:8848
#        username: 'nacos'
#        password: 'nacos'
#  main:
#    allow-bean-definition-overriding: true
##  config:
##    import:
##      - nacos:service-consumer-2023.properties?refreshEnabled=true
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#logging:
#  level:
#    com.alibaba.cloud.nacos.configdata: debug