server:
  port: 65100

spring:
  application:
    name: service-provider-2023
  cloud:
    nacos:
      username: 'nacos'
      password: 'nacos'
      discovery:
        enabled: false
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
        serverAddr: 127.0.0.1:8848
        username: 'nacos'
        password: 'nacos'
#  config:
#    import:
#      - nacos:service-provider-2023.properties?refreshEnabled=true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug